---
- name: Deploy Scientific Calculator Container
  hosts: production
  become: yes
  vars:
    app_name: scicalc
    image_name: sparshdockerman/scicalc:latest
    container_port: 8080
    host_port: 8080

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Pull latest Docker image
      ansible.builtin.shell: |
        docker pull {{ image_name }}

    - name: Stop existing container if running
      ansible.builtin.shell: |
        docker stop {{ app_name }} || true
        docker rm {{ app_name }} || true

    - name: Run new container
      ansible.builtin.shell: |
        docker run -d --name {{ app_name }} -p {{ host_port }}:{{ container_port }} {{ image_name }}

