---
- name: Deploy Scientific Calculator CLI Application
  hosts: localhost
  connection: local
  become: yes

  vars:
    app_name: scicalc
    image_name: sparshdockerman/scicalc:latest

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Pull the latest image
      ansible.builtin.shell: |
        echo "🔄 Pulling latest image: {{ image_name }}"
        docker pull {{ image_name }}

    - name: Stop and remove existing container if running
      ansible.builtin.shell: |
        echo "🛑 Checking for existing container..."
        if [ "$(docker ps -q -f name={{ app_name }})" ]; then
          echo "Stopping container..."
          docker stop {{ app_name }}
        fi
        if [ "$(docker ps -aq -f name={{ app_name }})" ]; then
          echo "Removing container..."
          docker rm {{ app_name }}
        fi

    - name: Run new container interactively
      ansible.builtin.shell: |
        echo "🚀 Starting interactive Scientific Calculator..."
        docker run -it --name {{ app_name }} --rm {{ image_name }}
      args:
        executable: /bin/bash
      register: run_output
      ignore_errors: yes

    - name: Display container output (if any)
      ansible.builtin.debug:
        msg: "{{ run_output.stdout_lines }}"
